import { Text, View } from '@/components/Themed';
import Colors from '@/constants/Colors';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { StyleSheet, Pressable, Image, ScrollView } from 'react-native'; // --- 1. Importar ScrollView ---
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient as ExpoLinearGradient } from 'expo-linear-gradient';

// Forzamos el tema oscuro
const theme = 'dark';
const themeColors = Colors[theme];

// --- NUEVO: Componente de Mockup de Cita ---
// Esta es la "captura de pantalla falsa" que mencionaste
function MockupPreview() {
  return (
    <View style={styles.mockupContainer}>
      {/* Perfil Falso */}
      <View style={styles.mockupProfileCard}>
        <Image
          // --- CORRECCIÓN DE RUTA ---
          // Necesitamos subir 3 niveles: (tabs) -> (app) -> app -> raíz
          source={require('../../../assets/images/mock_profile.png')}
          // Por ahora, usamos un ícono
          // source={{ uri: 'https://placehold.co/100x100/C039FF/FFFFFF?text=A&font=inter' }}
          style={styles.mockupImage}
          onError={(e) => console.log('Error loading local image', e.nativeEvent.error)}
        />
        <Text style={styles.mockupName}>Amanda, 24</Text>
        <Text style={styles.mockupBio}>
          "Loves hiking, pineapple on pizza, and bad jokes."
        </Text>
      </View>

      {/* Respuesta Falsa de Rizzflow */}
      <View style={styles.mockupRizzBubble}>
        <Text style={styles.mockupRizzLabel}>
          <Ionicons name="sparkles" size={16} color={themeColors.tint} />
          {' '}Rizzflow Suggestion
        </Text>
        <Text style={styles.mockupRizzText}>
          "Are you a national park? Because I'd love to get lost exploring with you. (And I'll bring the pineapple pizza 🍍)"
        </Text>
      </View>

      {/* Resultado Falso */}
      <View style={styles.mockupMatchBubble}>
        <Text style={styles.mockupMatchText}>
          <Ionicons name="heart" size={16} color={themeColors.accentRed} />
          {' '}New Match!
        </Text>
      </View>
    </View>
  );
}
// --- FIN: Componente de Mockup de Cita ---

export default function HomeScreen() {
  const goToRizz = () => {
    router.navigate('/(app)/(tabs)/rizz');
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      {/* --- 2. Cambiar View por ScrollView --- */}
      <ScrollView 
        style={styles.scrollContainer} 
        contentContainerStyle={styles.contentContainer}
      >
        
        {/* --- Mockup Añadido --- */}
        <MockupPreview />

        <Text style={styles.title}>Welcome to Rizzflows</Text>
        <Text style={styles.subtitle}>Your AI-powered dating assistant.</Text>

        <View style={[styles.infoCard, { backgroundColor: themeColors.card }]}>
          <Text style={[styles.cardTitle, { color: themeColors.tint }]}>
            <Ionicons name="flash" size={20} color={themeColors.tint} />
            {'  '}How it works:
          </Text>
          <Text style={styles.bulletPoint}>
            • **Upload any screenshot** (Tinder, Bumble, chat, etc.)
          </Text>
          <Text style={styles.bulletPoint}>
            • Get **3-4 clever replies** generated by AI instantly.
          </Text>
          <Text style={styles.bulletPoint}>
            • **Tap to copy** and paste it directly into your chat.
          </Text>
        </View>

        {/* --- Botón de Acción Principal --- */}
        <Pressable style={styles.buttonWrapper} onPress={goToRizz}>
          <ExpoLinearGradient
            colors={[themeColors.tint, themeColors.secondary]}
            start={{ x: 0, y: 0.5 }}
            end={{ x: 1, y: 0.5 }}
            style={styles.buttonGradient}>
            <Text style={styles.buttonText}>Get Started</Text>
            <Ionicons name="arrow-forward" size={20} color="white" style={{ marginLeft: 8 }}/>
          </ExpoLinearGradient>
        </Pressable>

      </ScrollView>
      {/* --- 2. Fin del cambio --- */}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: themeColors.background,
  },
  // --- 3. NUEVOS estilos para ScrollView ---
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
  // --- 3. Estilo 'container' renombrado y modificado ---
    // flex: 1, // <--- Eliminado
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: themeColors.background,
    paddingTop: 10,
    paddingBottom: 40, // <--- Añadido padding inferior
  },
  // --- NUEVO: Estilos para el Mockup ---
  mockupContainer: {
    width: '100%',
    backgroundColor: themeColors.card,
    borderRadius: 24,
    padding: 16,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  mockupProfileCard: {
    backgroundColor: themeColors.background,
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    width: '90%',
  },
  mockupImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: themeColors.tint,
  },
  mockupName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: themeColors.text,
  },
  mockupBio: {
    fontSize: 14,
    color: themeColors.icon,
    textAlign: 'center',
    marginTop: 4,
  },
  mockupRizzBubble: {
    backgroundColor: 'rgba(192, 57, 255, 0.15)', // Fondo púrpura claro
    borderRadius: 12,
    padding: 12,
    width: '100%',
    marginTop: 12,
    borderWidth: 1,
    borderColor: themeColors.tint,
  },
  mockupRizzLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: themeColors.tint,
    marginBottom: 4,
  },
  mockupRizzText: {
    fontSize: 14,
    color: themeColors.text,
    fontStyle: 'italic',
  },
  mockupMatchBubble: {
    backgroundColor: 'rgba(255, 59, 48, 0.15)', // Fondo rojo claro
    borderRadius: 99,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: themeColors.accentRed,
  },
  mockupMatchText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: themeColors.accentRed,
  },
  // --- FIN: Estilos Mockup ---
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: themeColors.text,
    marginBottom: 5,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: themeColors.icon,
    marginBottom: 25,
    textAlign: 'center',
  },
  infoCard: {
    width: '100%',
    padding: 20,
    borderRadius: 16,
    backgroundColor: themeColors.card,
    borderColor: themeColors.border,
    borderWidth: 1,
    marginBottom: 25,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  bulletPoint: {
    fontSize: 16,
    color: themeColors.text,
    marginBottom: 8,
    lineHeight: 24,
  },
  buttonWrapper: {
    width: '100%',
    borderRadius: 99, // Botón tipo "pill"
    marginTop: 10,
    shadowColor: themeColors.tint, // Sombra de color
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
    marginBottom: 15,
  },
  buttonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 99, // Botón tipo "pill"
    width: '100%',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
});